# Generated by Django 3.2.7 on 2021-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.IntegerField(default='00000'),
            preserve_default=False,
        ),
    ]
