# Generated by Django 3.2.8 on 2021-10-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211025_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['placed_at'], 'permissions': [('cancel_order', 'Can Cancel Order')]},
        ),
    ]
