# Generated by Django 3.2.7 on 2021-09-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0004_alter_tag_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='tag',
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='attached_file',
            field=models.FileField(null=True, upload_to='tags'),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype'),
        ),
    ]
